<RootWidget>:
#make widget take up whole screem
    canvas.before:
        Color:
            rgba: 0, 0, 0, 1
        Rectangle:
            # this implicitly binds the size of the
            # rect to the size of the widget
            size: self.size
            # self here still refers to the widget as Rectangle is only a
            # graphics instruction and not a widget
            pos: self.pos
    #make sure child widget takes upp full space
    #horzitnail boxlayout

    size: root.width, root.height
    BoxLayout:
        size: root.width, root.height
        
        # will tkae up 0.5 horziontal space but fill width verticaly
        size_hint: (1, 1)
        BoxLayout:
            orientation: 'vertical'
            id: v1
            size_hint: (0.5, 1)
            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
            # this implicitly binds the size of the
            # rect to the size of the widget
                    size: self.size
                # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                    pos: self.pos
            #temp widget
            Widget:
                canvas.before:
                    Color:
                        rgba: 0.3, 0.3, 0.3, 1
                    Rectangle:
                # this implicitly binds the size of the
                # rect to the size of the widget
                        size: self.size
                    # self here still refers to the widget as Rectangle is only a
                        # graphics instruction and not a widget
                        pos: self.pos
                size_hint: (1, 0.5)

        BoxLayout:
            orientation: 'vertical'
            id: v2
            size_hint: (0.5, 1)
            #temp widget
            BoxLayout:
                size_hint: (1, 0.5)
                orientation: 'vertical'
                Label:
                    text: "Marker Translation"
                    size_hint: (1, 0.2)
                    canvas.before:
                        Color:
                            rgba: 0.4, 0.4, 0.4, 1
                        Rectangle:
                    # this implicitly binds the size of the
                    # rect to the size of the widget
                            size: self.size
                    # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                            pos: self.pos
                
                #traslation
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint: (1, 0.3)
                    canvas.before:
                        Color:
                            rgba: 0.1, 0.1, 0.1, 1
                        Rectangle:
                    # this implicitly binds the size of the
                    # rect to the size of the widget
                            size: self.size
                    # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                            pos: self.pos
                    Label:
                        id: vx
                        text: "X"
                    Label:
                        id: vy
                        text: "Y"
                    Label:
                        id: vz
                        text: "Z"
                Label:
                    text: "Marker Rotation"
                    size_hint: (1, 0.2)
                    canvas.before:
                        Color:
                            rgba: 0.4, 0.4, 0.4, 1
                        Rectangle:
                    # this implicitly binds the size of the
                    # rect to the size of the widget
                            size: self.size
                    # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                            pos: self.pos
                BoxLayout:
                    size_hint: (1, 0.3) 
                    orientation: 'horizontal'
                    canvas.before:
                        Color:
                            rgba: 0.1, 0.1, 0.1, 1
                        Rectangle:
                    # this implicitly binds the size of the
                    # rect to the size of the widget
                            size: self.size
                    # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                            pos: self.pos
                    Label:
                        id: ax
                        text: "Pitch:"
                    Label:
                        id: ay
                        text: "Yaw:"
                    Label:
                        id: az
                        text: "Roll:"
            BoxLayout:
                size_hint: (1, 0.5)
                orientation: 'vertical'
                spacing: 10
                padding: 0, 0, 0, 10
                canvas.before:
                    Color:
                        rgba: 0.2, 0.2, 0.2, 2
                    Rectangle:
                    # this implicitly binds the size of the
                    # rect to the size of the widget
                        size: self.size
                    # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                        pos: self.pos
                Label:
                    text: "Options"
                    size_hint: (1, 0.2)
                    canvas.before:
                        Color:
                            rgba: 0.4, 0.4, 0.4, 1
                        Rectangle:
                    # this implicitly binds the size of the
                    # rect to the size of the widget
                            size: self.size
                    # self here still refers to the widget as Rectangle is only a
                    # graphics instruction and not a widget
                            pos: self.pos
                Button:
                    size_hint: (1, 0.4)
                    text: "Zero Marker"
                    background_normal: ''
                    background_color: 0.1, 0.1, 0.1, 1
                    valign: 'middle'
                    on_press: root.tracker.zerovalues()

                ToggleButton:
                    size_hint: (1, 0.4)
                    text: "Record Data"
                    background_normal: ''
                    background_color: 0.1, 0.1, 0.1, 1
                    on_state:   root.tracker.togglerecord(self.state)
